services:
  - type: web
    name: orveyra-health-platform
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
